In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [7]:
import numpy
n = numpy.arange(27)

In [11]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [13]:
n.reshape(3,9) #two dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [14]:
n.reshape(3,3,3) # 3 dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [16]:
m

array([[123, 12, 123, 12, 33], [], []], dtype=object)

In [17]:
print(m)

[[123, 12, 123, 12, 33] [] []]


In [18]:
type(m)

numpy.ndarray